### Login (obter token JWT e salvar)
@protocol = http
@hostname = localhost
@port = 8080
@host = {{protocol}}://{{hostname}}:{{port}}
@contentType = application/json

###
# @prompt email
# @prompt password
# @name postLogin
POST {{host}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

@token = {{postLogin.response.body.access_token}}

### Acessar endpoint protegido usando o token capturado
GET {{host}}/protected
Authorization: Bearer {{token}}
